apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:h6suPUqk1ooNV551q23pHdYKSl5ZGfw33nIUMRVU0F0P7ElzRHCFtA==,iv:vf4h4FsqfIg5iWVP0lgAJEIp0Mv1g6Y4ftRiKd+92n0=,tag:e9rT8Lfe5CX+ZBAIuBYpfQ==,type:str]
sops:
  age:
    - recipient: age12xg36efrledrxuh7722kwr2973tvp0yzhay4cnfhanzwq4m89g6s63r90a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbnZWWStlOHlkM1RlRTR6
        RXh1clFUUTlxcDJicVEzb1ByaFUwRW5RNERjCm1Wem9BMmtVQ0M4NFo4M1NhOXRn
        bmd1TUlxaXV4bGp5Q3YyWWx2YzRqODAKLS0tIHI4U1FZaHY5V0l6UjRpUS85REhz
        UExHRlA3NXRmSVBraFIwVTUxWS9xaHcKar4Gu/l+x7jg1h6urTiLZHC/rhgHF9ER
        K4iESYixXCKHj1g4JWADKREnSFGyWoU5ijHFdJQ6aNhXEjZVM4qmmg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T11:19:13Z"
  mac: ENC[AES256_GCM,data:s4OEAbnp6rrK3Scnt/ZB2LTPvfl3C5KGlxya00gPJ3L/H4Y/HA3qS1OhZS//QT2s6Zx5jQi+q8C2kahfDsxVS61ZHR78LeHxsTVgsInljNv1jLc/g0i7Pz03dwaMQ/aX9UyiOcmaWpxVJEXR3R1nUhTxW0PvVoMC6ZOYlG+KYhU=,iv:hRQaiuoQMNII/hxer3l/JL/sJXa41fE3V7Xl10kty8E=,tag:rSjAHaDBWw19r2KzZdJ0zQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
