apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:RASrBdrIWauV/9suQ3O8Jk9N6idmQYhwZYai+K1r39CTevPVU5wSpQ==,iv:qNleBwbLBtdCEQ8oKSUgzg6ADAAYv1VREqMoHPNaBCw=,tag:ciqveGs1+is99hsvzdRY5Q==,type:str]
sops:
  age:
    - recipient: age12xg36efrledrxuh7722kwr2973tvp0yzhay4cnfhanzwq4m89g6s63r90a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2elVXZUJhV09FKzlzMmw1
        WWliYjgxZnMrc2JhZGovMEZCYWp5eUhIc0JFCnBIbWZxTzdMSnNvd2FrU212Z0I0
        aForbk1nd1BUUGRBWnRFQWdPQnB1UjQKLS0tIEdaa2E4Q1dJckc5bWZqeWdqc1lG
        QnNuaW9FUldqdm9KY1U4WWt2N1RZMEkKQpNFvjTM+0RCuLeSKLKScrOQ3o+e50xW
        KKb+qEiyKrPz2AxcIUEGmeWEXaYbPtXIYwffgizne8Ovp3HhZpZXFA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T11:31:30Z"
  mac: ENC[AES256_GCM,data:e0dWG4P4GfCVgfD7SDrwvAnsjK+VrFqji96wLrezYnZMmk8vap1S5YM4jdnaqWK7spgyqLAV2urfkNuDFFrDgnKl7peTWa6a3EJRYpKAZQvB8aE8CBdYSubyEGYP9GA1Q1ozqE9l/B49UjXEv3FXux2kSh97qBP6MicC1SF7Fbw=,iv:iCXtHcoL+rtXhiABKXrKfNZZ5TSD5n46v68Gf++Pveg=,tag:6EVNdDDGX1yyuwc2wGpxKw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
