apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:yfQizNJK8CnyBQ==,iv:rXgQdmuVg6NYa5Da8Vlr7E9Sg6jdbUJ6g/bteJoSY48=,tag:mujqby3yar1CWwGVY2oR6g==,type:str]
sops:
  age:
    - recipient: age12xg36efrledrxuh7722kwr2973tvp0yzhay4cnfhanzwq4m89g6s63r90a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSS81UCs3aUxVY0s2VWJB
        YUNzbmFmbHY5ZmtGUTN1Zi9FZzdNaGREeFQ4CkNJVGtKd2ttdXlPZFlybmNXRmtB
        Q1lUNXR0RThuVXkzWm1CeEJIR0hrZE0KLS0tIGNuZWMyU2liWFA0bFdtTTZJU3ZU
        OGkzWkdOM1ZDVjFNRHNWa1VxL1JPaUEK6B5/YixoH3k3XjfGbhVmIRKJB++nKktT
        4+V9+uf+5XzrEB49Bk5g1Cey+CCeFB5xV9WiRl+P0vetKrq9Uqq3mQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T11:19:13Z"
  mac: ENC[AES256_GCM,data:MC2EpmWtjAtok8z/N55WfXN/IB+CSG+oUruaXOEmNLeOD05Ut3tAkIogXopHAOq6CXBabQus+tWo4ReG3QoV2IBQC85yKUw2uLbw5hoIQXVebRPeEc7gD7QQKho0JuPPn//CNmc2vN+JKHPoXYWZxq4bXDWcdJcc1/blXUotvgs=,iv:1mfbenQ6ufcKSPDL84Ze7D3c4TV7a2Ec6c1YHyVn6LQ=,tag:awMLq8QvFcezJrfTRUoTGA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
