apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:19cXSPaY7eNvQSe45nik2M1GEJvsKIxIuOKYdxx8flU=,iv:87HdPN+8kcsDxwTm+pFGrDVAI7o+BlW9yBaWeCW/45E=,tag:YMbxRyuOxQt0iRpLgDOfSQ==,type:str]
sops:
  age:
    - recipient: age12xg36efrledrxuh7722kwr2973tvp0yzhay4cnfhanzwq4m89g6s63r90a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbGJscHd1bG1uWWg4K0Jy
        WXliS1Zydm5Ra0hxb1NlK1VoeElyNEExQjMwCjhYM1ZhSTE5bzE2cVVOSDgzTmdw
        K3lvQmdBQVg2Vnl2U0ZnMFJXZW5wL28KLS0tIHpsT0VKWGpWUDY0bzdKUWFMVWtB
        SGxMNHJXNTdxOEFMMVhtK3Y5MW1uczgKho172k1EcRzZGwzUPJ8EXcEOa2mQVr78
        CuKPJ6fqf58CCl9HURAi1+zWrEx+iDKR4RDW3ziboEc5v8zsRMckvg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T11:19:13Z"
  mac: ENC[AES256_GCM,data:14O3Du8jbmqh6EfbATnwJSI8code9Q0nQPGfcmfudr2k+HDz7pjai12YVHsjdWeJVOfCFe5ln5/UtEIK3GL0VzgEdhllPVrcz47qCWQFlgEaAoH7yOugt2lKDm3d7ooV0OukCDtgdv3WQV1uNyQkxucGTjo/MgdgkpENqzwjOqQ=,iv:Zd1lw9YDEUq1hJxsGZZeEBtZbGeI/MmtyOWoEnB9AlU=,tag:jxr9uoxrobW6J4U7LDNqSQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
