apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:X/libiJyD7Lss++89ZRD5XaSZSIJhvKi+VcZ1XT4/FM=,iv:LKLXLjhTImMB8LypPp4PaMAOdPdCe2Q1UjWueluuQ1Q=,tag:HcujD5JTuX/OC/BkxSz57g==,type:str]
sops:
  age:
    - recipient: age12xg36efrledrxuh7722kwr2973tvp0yzhay4cnfhanzwq4m89g6s63r90a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZURCcGo4b0tMWGt2Ulow
        d0VoLzA1U1l2ZC9tdTJ3WThEQVRxS1hWTUZRCjhxSCttZmNUNE1YaFZ1NU5pN1JO
        R0Y0VWpnb0EvQzZJS1hjSmg2NVp6RmsKLS0tIE9sblFZOWVUMmNNUXRyckdiRkdv
        WFI2bVZpYnNtRjBFY1NyMTB2ZUp3MEkKYPrlcD0cdtkWCEmcC3XUeELMzuU9srOi
        IRab4xx4Yz12PywG7oelKTJO0sjbK6scIeBX1lCJ73Si/sJjetKf0w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T11:31:30Z"
  mac: ENC[AES256_GCM,data:wzLiomsZ7urTb/P+fh/XH6o+2Co19dwBDoe2HJ8c9i+i3Q9N1yTCIcUgW1hk33jECUnAHN76gzRUnO4B69Axu1JnVVCF4JX8haPIwIhPHB70HJdaCZxJM8aNiNrDTPG9qpgc0Q0S1ytoMdV3xHl9wXcUUiRV9OMLhpkPMwlVjAo=,iv:VvvM68jVVq4OrzaTy1dHFr8gdHARdyhS31bSh2NCPDw=,tag:lf5D4oejFimMm6Gl0vurxA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
