apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:jcM9BS9LjpimBdMtzS/OdiCXQ6NueOBOuix7w/AatRn0CEWJ679Qtps3uaoEryuaFBXtyCTzNkbY6lIKa5vHuK+QO3lgq4AXwHEOzgQoG5APnpOSnmXTra5h/t22uIEKc6TWGuPZyV3w91BRzPOoDa21JPJ9jhCJEn1BkiWMGwE3UfUVBvGA29zdqccfXurYaqGzfzmxY3s+vYlBT7ZO2DqyhZ5EAkMM89KLNz7B72001Rro,iv:zQ702Okev+JXFcYojpZE8FUYHgRJq+T3FJDIdMVyvjg=,tag:0huVmC88j4mP1FK2Jz8ixQ==,type:str]
sops:
  age:
    - recipient: age12xg36efrledrxuh7722kwr2973tvp0yzhay4cnfhanzwq4m89g6s63r90a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMGg2bW9FbkxDaHgvdUlH
        ay9QdEdPUENyYmRhekxYUmZKNk0zY2RHSEZVCk1LQzZmZW5mbkdmNWpKRld1UElv
        WjJRWGZ0a0xQR3dkcEdGSVhLNFZjQTAKLS0tIGowSjM3OW1MWWNXekFzUys0ZVBq
        SkhjSi80c21VK0dVY2lWTThna0xRMVkK2eTHI672JebzQiM4pBRU3x1t043lcZwi
        4alZLsBpCGEsFmIWCT9lE0MINNiq7xCYrBnZbbEnzLdVgV/CpQJvdg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T11:31:30Z"
  mac: ENC[AES256_GCM,data:7/ckPMTM+R9P52DOARqZsy5Kk/RORuSgvxM1QhmsfTbXSgnBB4dBhcdPIKhiR5Sm9yMVRhYnWSg8PIaUlg5ZTrcAwgjtr3mZ+lCqiqlhFwenvtTraHkhahLVH5PnWX6ulh+F548oC1Ympm0wPIHdKrkwl/mFu3j/DY9p7uXsfBM=,iv:184clan/brn45ZO9rlfCzwWjP6OezaJqtXL4DLvjH1g=,tag:U5wyxXWCTAcuzCAqXYJ6cg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
