apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:NbCgwD3GBsCz3SFiAaROpsFaSfj9w/dNs7sxaiYqGoQ1IdBkNiy+djWlPkbRxB9MBrHTEXo9FBmGhJwj9PTmiH/UsNIQGMF2nw1I45kOO/YtXxyeEONRLTH/VudsOcKVH107yEnysXeQzSwd4pGQf9L3A7Fjnsgu+IDN8CAEGaTwAEfqbqTDqznT+QhPOYXyRerYWkQKHGuKg5tdmePN92u9C0S2OclS2dJxakJgs7MMgMbT,iv:OlTHjIUQMuwMB0kvDj6exul8MgeT1kvLai30ZSFRaUs=,tag:o/EtFh4Z3jSieot840KUmw==,type:str]
sops:
  age:
    - recipient: age12xg36efrledrxuh7722kwr2973tvp0yzhay4cnfhanzwq4m89g6s63r90a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXT3ZyK0UvUFY3enZnTmRx
        UFh6V3o5dXpORDNOUjBrdkNRUTNHYkV6ZWhRClZHdjhKVmM4WW9zQWpSNFJsMDFV
        R3FaV2ptVmw1QXpralRYMWoybk41YUEKLS0tIEtSVFJPeTAzQzlsajhmL3E5U1BI
        bVlDeDlTMGFFM1dyd29ReG9iQUtoMGsKepeQXpeInQz0NSCQ87x+oNjYHO1uq6dN
        tdtlZFmEVuM1AJwlQROfxZEwgFrf3yqMv0p5BwzZKYcio9LjYOlwEQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T11:19:14Z"
  mac: ENC[AES256_GCM,data:0xjD4qw8ut89Qyu3xmkI7w0z9BWsilkrRP8dAaYbQXnZ6vYAZ/PMy3DLp3pZGctzQYCasRx+QDbNwlGS2dYsuYNPhTxkxeVWfs4ZarXAmHAgFQhNI1aqn077Pxa0sOaL4e6Xwks6pAW3jA+XNYjUCPcYdC8ClBik8D//97/P3Yg=,iv:L8lxN6CJVxuIYcu6bLH7TfEWl7xNU46FA0hPd/n0kxE=,tag:PJhYAJ8yRME+nzUTwXMckw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
