apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:A7AFOIjVELIweUuHp9P+EAM87kaDRfgh41qjKK/kAq/5exVfd51e1g==,iv:eN8qhT/wnH0lBeRUIGbPPIsrNyusFqFcDU3Po+wUknw=,tag:PirNTSWxhGP3fAso93dSOA==,type:str]
sops:
  age:
    - recipient: age12xg36efrledrxuh7722kwr2973tvp0yzhay4cnfhanzwq4m89g6s63r90a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TFczTFZzYnpWSjJjU01x
        TzRuam9iaUNnTThUREJuRDUrV0RuazgyRmtFCjVjLzN3b2VPTUxMK011NktNeEFh
        clo3TGU5ejcvM3JabXZzVVhzbVRiVmcKLS0tIG12T1NvbFpnKzB6a0NOMC9oeVJ5
        VDZRdHE4a05OYS96S01qblpVUGxKT0EKrLpRs8OFGf8Uag7MoXbZklQJJNuDGG0S
        hF43pBli2ah+OJoyd0R6UL7FRlpOD9kRJOBB7WOFqd+VBPDBJuYvEQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T11:31:30Z"
  mac: ENC[AES256_GCM,data:cnUQvpgcfOUFv70ON+Qap/XiRT1oNZ1OjET7pp6euOTF9IwcVfWmzOTz2buu5F15/Yz7Fg7OEp8BQNicXU9acCZ7hzAUecNe42dlYCdFwNdvgN+ZxmLGojTsyE4oJiU1b7uiTbrp4bN9akWFbK7EEQEVxH0OgzvsOp2p9BWvNlE=,iv:GqcyewGZTxR+9WaYydMpNkWOAPKwiR4qnc9CVSse2zs=,tag:9NShJXMmv6zH7nn6GP3nzg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
