apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:uYGFda+3hlt6WUV8trfuvA3+UemymAOrGiIGNr2W9zKIV4/NGzj9Xg==,iv:Aehi8xoEfy7oxMnoX6FB5xELsXsImh8Bs0uWcjuVtvo=,tag:prw12twPz0br97UQv/zoEw==,type:str]
sops:
  age:
    - recipient: age12xg36efrledrxuh7722kwr2973tvp0yzhay4cnfhanzwq4m89g6s63r90a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWXFuQUIyY05oSjRISENI
        U2VRK21IRkRZbjRycDB4ek1jNnpUeEErTGdjCnAxdWwycm1TbzZ1T2syclNCZkJs
        SWtRQ0IrT0dFUkVUcXNia1dtVlgrSEkKLS0tIGhNaHU3SmpwcGZDL1kxNlQvRGpI
        T0N0STNaQ0s0VENBaThIS2VoUmdtakUKqWicJE+WYIot7gQ5pT7oaCspOlhQJ82a
        PKsKhZBQZ+6QrNncA5B4fp2pLTD/bZAqJHXFrW32PRrbVYzkBmqcdQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T11:19:13Z"
  mac: ENC[AES256_GCM,data:xqqqusooko6CyMNZvIm5zDYOCjNdV69rtJy+1icPSxl83cwJCjDmHH4eQSjpRndBX2BfoGxF6N1CkrhTt1BzAMXBeuYtuceD+ri7EBJZmg0vVJx+TTtRjtIQrkWgNoq7zou16hPdBbaRQI1S5HGFKO0Wjec+cTGoAexCaG8Eqk8=,iv:0nXQNLZIVd4buyiLdm+lz4GI/vPqCGXmH+llT81JQWE=,tag:pWe7g11UxgurZp6/HGvRRw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
