---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-synology-csi
  namespace: flux-system
spec:
  path: ./kubernetes/apps/storage/synology-csi/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 15m
