apiVersion: v1
data:
  client-info.yml: ENC[AES256_GCM,data:52bjgB618PpJIIcPozU4G8r+KKKKTruD4EWUpFfHf/ml1Zv5PXuv9xoHASS5Whkegkfk5c/lScsws8y/2jaNrrxKBvgarMJi5xWrACuV2RvKsE51DmESiuB2unWv3FKytM3CAyC1QPZV9t/V4izDc4E9/Ts6EJVk+dvBiNJgnAkWwlX2,iv:Ei2LV1LzjSfUksB/lxW3EzAZwJzVDNzDg/l3jHVuhbc=,tag:JAv0GUMZeKejHW1+Ms4INw==,type:str]
kind: Secret
metadata:
  name: synology-csi-client-info
  namespace: synology-csi
sops:
  age:
    - recipient: age12xg36efrledrxuh7722kwr2973tvp0yzhay4cnfhanzwq4m89g6s63r90a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMCs0dURZd0x5SEs0T0NK
        TjFVMnJPY0FzSzJneWxIOWtuQ1pmV2U1clVNCm5Ma1lKT2xZRTZTWDNZKzdIMWtY
        RU5Ba0t0cVZPT0xtdnNOeXpjWUZyejAKLS0tIDR2L2xYUjhMQWNjV3p4TWVHM1Bk
        bXo1Mzc2Y1VrN0tNbWttM0NOMmloTjAKZWsqszzaSYucB1vtql7qbjo5lf6fVvG/
        xH2jbDh4RSygN3mhle+WFfO8jPBeY4gRiyknPEExYNwzALv81gM2rw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-22T17:47:44Z"
  mac: ENC[AES256_GCM,data:Fv1Kb0F9n28NOisVBXC9TVeRS6RDnjgAzeucHuWRc6i+ujLJdFaJa8ml9GFgeWW7AANJIhNeU4+mHUKaUOUVLpNhPdAz5p22YCFz3gwIACgd8Vo8Gnf659WQhIHEW+puPPWtzeg6mIPAUrSuZSv1lbWc5BpVLeqrLQLuq4ILVvo=,iv:udi6XdxE7Lw7Gok25XSdfzfi+g7b/q32607aZqPikZM=,tag:jFWGB3U4DONRHAN0CDeJgQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
